language: python

python: 2.7

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

install:
  - pip install beautifulsoup4 lektor requests

script:
  - "python scripts/check_links.py"
  - "lektor build --no-prune"

deploy:
  provider: script
  script: "lektor deploy ghpages-https"
  on:
    branch: lektor
