# https://travis-ci.org/pybee/pybee.github.io/builds
language: python

python: 2.7

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

install:
  # Lektor build dependencies
  - pip install lektor pygments

script:
  # Only do the checks if this build is the pull request not the merge!
  - if [[ $TRAVIS_PULL_REQUEST == "true" ]] && [[ $TRAVIS_BRANCH == "lektor" ]]; then
      "pip install beautifulsoup4 requests"  # Additional test dependencies
      "python scripts/check_links.py";
    fi
  - "lektor plugins reinstall"
  - "lektor build --no-prune"

deploy:
  provider: script
  script: "lektor deploy ghpages-https"
  on:
    branch: lektor
