name: CI
on:
  pull_request:

jobs:
  check-links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.X'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools
        pip install lektor pygments
    - name: Check links
      run: |
        lektor plugins reinstall
        lektor build --no-prune
